version: '2.1'
# Elasticsearch stack designed for container-native deployment
# using the Autopilot Pattern on Joyent's Triton platform.

# ---------------------------------------------------
# This common service definition is the default for nodes that both store
# data and act as potential masternodes. It also serves as a template for
# master-only and data-only ES nodes.
services:
  es:
    image: autopilotpattern/elasticsearch:test
    mem_limit: 4g
    restart: always
    labels:
      - triton.cns.services=es-master
    network_mode: bridge
    environment:
      - ES_SERVICE_NAME=elasticsearch-master
      - CLUSTER_NAME=elasticsearch
      - ES_NODE_MASTER=true # default
      - ES_NODE_DATA=true   # default
      - CONSUL_AGENT=1
      - CONSUL=ec.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}
      # set the number of threads we want based on the number of CPU shares
      # that we'll get for this size container on Triton
      - ES_JAVA_OPTS=-Xms1g -Xmx1g -XX:-UseGCTaskAffinity -XX:-BindGCTaskThreadsToCPUs -XX:ParallelGCThreads=1 -XX:ParallelCMSThreads=1

    command: >
      /usr/local/bin/containerpilot

  # ---------------------------------------------------
  # The master-only node serves as the coordinator of the cluster only

  es_master:
    extends:
      service: es
    labels:
      - triton.cns.services=es-master
    environment:
      - ES_SERVICE_NAME=elasticsearch-master
      - ES_NODE_MASTER=true
      - ES_NODE_DATA=false

  # ---------------------------------------------------
  # Data-only nodes never act as master nodes.

  es_data:
    extends:
      service: es
    labels:
      - triton.cns.services=es-data
    environment:
      - ES_SERVICE_NAME=elasticsearch-data
      - ES_NODE_MASTER=false
      - ES_NODE_DATA=true

  # ---------------------------------------------------
  # Consul as a service discovery tier
  consul:
    image: autopilotpattern/consul:${TAG:-latest}
    labels:
      - triton.cns.services=ec
    restart: always
    mem_limit: 128m
    ports:
      - 8500
    network_mode: bridge
    environment:
      - CONSUL=ec.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}
    command: >
      /usr/local/bin/containerpilot
